### ISSUE TITLE
`.ssty` should not be detected as size alternate

### ISSUE THREAD

**Issue by khaledhosny** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#19]

**Comment by schriftgestalt** [comment]
If it is useful, I can change the change it that the plain .ssty suffix is picked up for the feature code. I was not sure about this the other day.

**Comment by khaledhosny** [comment]
> If it is useful, I can change the change it that the plain .ssty suffix is picked up for the feature code.

That would be helpful (though it is not related to this issue, which is about MATH size variants and I was incorrectly grouping `.ssty` with `.s01` etc. glyphs).
