### ISSUE TITLE
Dialogs look broken

### ISSUE THREAD

**Issue by khaledhosny** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#22]
I don’t know what changed (Vanilla) but dialogs are currently broken:
<img width="762" alt="image" src="https://github.com/Nagwa-Limited-Community/Glyphs-MATH-Plugin/assets/93914/8cf73095-87a8-4b07-8e59-272f37b4dbab">
<img width="762" alt="image" src="https://github.com/Nagwa-Limited-Community/Glyphs-MATH-Plugin/assets/93914/55792f11-e312-4090-8d9e-9b0619773252">

**Comment by khaledhosny** [comment]
@schriftgestalt I don’t know if this is related to Glyphs or Vanilla updates, but I changed nothing in the plugin recently.

**Comment by schriftgestalt** [comment]
I updated vanilla. So that definitely changed in the last weeks. 
Do you use the vanilla from the Plugin Manager?

**Comment by khaledhosny** [comment]
> I updated vanilla. So that definitely changed in the last weeks.

Things were fine a couple of days or so ago.

> Do you use the vanilla from the Plugin Manager?

Yes.

**Comment by khaledhosny** [comment]
Did you find a fix/workaround for this?

**Comment by schriftgestalt** [comment]
I posted that in the vanilla issue that leads to the change that caused this but nobody answered. So I can change the code in my branch to get it work but I don’t like to deviate again.

**Comment by schriftgestalt** [comment]
And I played around with the auto layout code to see if I can fix it. 
For me, the easiest would be to rebuild the UI in Xcode ;)

**Comment by khaledhosny** [comment]
> For me, the easiest would be to rebuild the UI in Xcode ;)

I’m not opposed to that (it is actually something I wanted to do long ago as I find controlling UI widget using code to be very frustrating), but I wouldn’t know where to start.

**Comment by schriftgestalt** [comment]
I had another look and I got it to work.
