### ISSUE TITLE
Localize the plug-in

### ISSUE THREAD

**Issue by khaledhosny** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#4]
Provide at least Arabic localization in addition to English.

**Comment by schriftgestalt** [comment]
There are two ways to do it. Put the localized strings into the code:
```
title = Glyphs.localize({
    'en': "Show MATH Italic Correction",
    'de': "Zeige MATH Italic Verbindung"
})
menuItem = self.newMenuItem_(title, self.toggleShowIC_)
```
That is fine for a smaller number of strings and keys. 

Or use `Localizable.strings` files and NSBundle to pick the right string.
```
NSLocalizedString("Show MATH Italic Correction", "")
```
(or make a shortcut like `NSLoc()`)
A Localizable.strings` file is put in a folder `en.lproj` `de.lproj` and `ar.lproj` (check the Glyphs bundle for available languages).
```
"Show MATH Italic Correction" = "Zeige MATH Italic Verbindung";
```
That setup is a bit more involved but easier to maintain. And has less clutter in the code.

What way do you prefer. I can help set it up.

**Comment by khaledhosny** [comment]
Thanks Georg, I appreciate your help. The second approach seems cleaner, so I’d go with that.

**Comment by florianpircher** [comment]
You can have a look at one of my plugins for the [.strings table files](https://github.com/florianpircher/Anchor-Annotations/tree/main/Anchor%20Annotations/ar.lproj) and the [use of those strings in code](https://github.com/florianpircher/Anchor-Annotations/blob/main/Anchor%20Annotations/ANANSettings.m#L67).

My code is in Objective-C, but the idea is the same with Python and pyobjc.

**Comment by schriftgestalt** [comment]
I just pushed a german localization. That includes the setup and some tooling to keep it updated.

**Comment by khaledhosny** [comment]
Thanks George, that is wonderful. I’ll see if I can add Arabic localization.
