### ISSUE TITLE
Interface Problem

### ISSUE THREAD

**Issue by n-botthof** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#5]
The content of both windows (MATHconstants and MATHvariants) is not displaying correctly.
_Tested on BigSur (11.7.1) and Glyphs3 (3187)_

MATH Constants:
The content is aligned to the bottom of the window, but the window does not resize to accomodate overflowing content. It also does not scroll.
<img width="762" alt="Bildschirmfoto 2023-04-19 um 10 29 57" src="https://user-images.githubusercontent.com/27273752/233018998-cc4dfa11-e068-48f6-ab6c-478034bd8f1c.png">
<img width="762" alt="Bildschirmfoto 2023-04-19 um 10 30 06" src="https://user-images.githubusercontent.com/27273752/233019030-5d3acbe5-f1ea-4370-8059-80060957cdc3.png">

MATH Variants:
This is what it looks like for me:
<img width="762" alt="Bildschirmfoto 2023-04-19 um 10 30 17" src="https://user-images.githubusercontent.com/27273752/233018883-1df7c70f-1b8d-48fa-bc45-18c8caf48285.png">
<img width="762" alt="Bildschirmfoto 2023-04-19 um 10 30 20" src="https://user-images.githubusercontent.com/27273752/233018930-6cfaaa58-8bde-4345-8f9b-1cf6f74914fa.png">

Could this have to do with Vanilla?

**Comment by khaledhosny** [comment]
I can’t reproduce this with macOS 13.3.1, and it was also working a few releases before. It is probably related to Vanilla, but I’m not very versed in Vanilla and might have used it wrong.

**Comment by n-botthof** [comment]
I updated to macOS 13.3.1 too now and the interface seems to be fine on this version.
