### ISSUE TITLE
Glyphs crashes on export

### ISSUE THREAD

**Issue by n-botthof** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#6]
Glyphs crashes as soon as I try to export an otf with Math-Variants. 
Adding constants does not make any problems – the file exports fine, but as soon as I add variants for one glyph it crashed on export. 

**macOS 13.3.1 Glyphs 3.2 (3187)**

**Comment by khaledhosny** [comment]
It is crashing for me indeed. It is been a while since I tried to export a font and I don’t know what changed. I’ll try to see if I can debug it or make a test case and send it to Glyphs developers, since it is the app that is crashing not the plugin’s Python code.

**Comment by khaledhosny** [comment]
This should be fixed in the latest cutting edge version of Glyphs, see https://forum.glyphsapp.com/t/glyphs-crashes-when-i-export-a-font-with-math-plug-in/25811/4
